name: Deploy Node application
 
on:
  push:
    branches: [ master ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Node App
        uses: fifsky/ssh-action@master
        with:
         command: ${{ secrets.COMMANDCHAIN_NODE}}
         host: ${{ secrets.REMOTE_HOST }}
         user: ${{ secrets.REMOTE_USER}}
         pass: ${{ secrets.REMOTE_PASSWORD}}
